name: CMake + GTest CI

on:
  push:
    branches: [ "main" ]  # or your branch
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
          path-type: mingw64

      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgArguments: "install gtest --triplet x64-mingw-dynamic"
          # The above command installs GTest for the MinGW-w64 triplet

      - name: Configure with CMake
        run: |
          mkdir build
          cd build
          cmake -G "MinGW Makefiles" ^
            -DCMAKE_TOOLCHAIN_FILE="${{ env.VCPKG_INSTALLATION_ROOT }}/scripts/buildsystems/vcpkg.cmake" ^
            -DVCPKG_TARGET_TRIPLET=x64-mingw-dynamic ^
            ..

      - name: Build with CMake
        run: |
          cd build
          cmake --build .

      - name: Run tests
        run: |
          cd build
          ctest -V
